config/routes.rb
Codemaptest::Application.routes.draw do  
	root to: "offline_schools#index"
  
  resources :offline_schools
	resources :online_schools
  resources :quotes
end

app/models/offline_school.rb
class OfflineSchool < ActiveRecord::Base
  attr_accessible :bio, :city, :ed_level, :format, :name, :pricing, :site_url, :state, :zip_code, :street, :latitude, :longitude, :languages, :contact_email, :contact_number, :country
  validate do
		errors.add(:name, "The school must have a name") unless name!=nil
	end
  geocoded_by :street
	after_validation :geocode
end

app/models/online_school.rb
class OnlineSchool < ActiveRecord::Base
  attr_accessible :bio, :ed_level, :name, :pricing, :site_url, :languages
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  attr_accessible :advice, :author, :education, :employer, :picture, :position, :years_programming
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/offline_schools_controller.rb
class OfflineSchoolsController < ApplicationController
	include OfflineSchoolsHelper
	
	def index
		@offline_schools = OfflineSchool.all
		respond_to do |format| #restful technique to
			format.html
			format.json {  
				@lat = params[:lat]
				@lng = params[:lng]
				render json: OfflineSchool.near([@lat, @lng], 50, :order => :distance)
			}
		end
	end

	def new
		getLatlng(params[:search_term]);
	end

end

app/controllers/online_schools_controller.rb
class OnlineSchoolsController < ApplicationController

	def index
		@onlineschools = OnlineSchool.all
	end

	def new
		@online_school = OnlineSchool.new
	end

	def create
		new_onlineschool = OnlineSchool.create(params[:online_school])
		redirect_to "/online_schools"
	end

	def show
		@onlineschool = OnlineSchool.find(params[:id])
	end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

	def index
		@quotes = Quote.all
	end

	def new
		@quote = Quote.new
	end

	def create
		new_quote = Quote.create(params[:quote])
		redirect_to index
	end

	def show
		@quote = Quote.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offline_schools_helper.rb
module OfflineSchoolsHelper
	#queries the googlemaps API passing through school address in the query string
	def getLatlng(search_query)
		query = URI::escape(search_query)
		result = Typhoeus.get("http://maps.googleapis.com/maps/api/geocode/json?address=#{query}&sensor=true")
		result_hash = JSON.parse(result.body)
		result_hash["results"].each do |result|
			@lat = result["geometry"]["location"]["lat"]
			@lng = result["geometry"]["location"]["lng"]
		end
	end
end

app/helpers/online_schools_helper.rb
module OnlineSchoolsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Codemaptest</title>
	  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "bootstrap" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.2/leaflet.css"/>
	  <script src="http://cdn.leafletjs.com/leaflet-0.6.2/leaflet.js"></script>
	  <link rel="stylesheet" href="../assets/font-awesome.min.css">
	</head>
	<body>
	<div class="row full-height">    
		<div class="col-md-3 full-height">
			<div class="sidebar affix">
				<a href="/"><div class='logo-container'>
					<i class="fa fa-map-marker"></i>
					<h1>learncode</h1>
				</div></a>
				<div class="links">
					<ul class="link">
						<a href="/quotes"><li><i class="fa fa-lightbulb-o"></i> Step 1: Get Inspired<br> <span class="small-text">Quotes from leading developers to inspire you</span></li></a>
						<hr>
						<a href="/online_schools"><li><i class="fa fa-pencil"></i> Step 2: Self Study<br> <span class="small-text">Resources to learn code on your own</span></li></a>

						<hr>
						<li><i class="fa fa-rocket"></i> Step 3: Get Real Training<br> <span class="small-text">Find a school where you can to learn to code</span></li>
					</ul>
				<form action="/offline_schools/new" method="get">
					<div class="input-group">
						<input class="form-control" type="text" name="search_term" placeholder="Where do you live?">
						<span class="input-group-btn">
							<button class="btn btn-primary">Submit</button>
						</span>
					</div>
				</form>
				<hr>
			</div>		
		<div class="footer">Are you a developer? <br> <a href="/quotes/new">Leave some words of wisdom</a></div>
	</div>
	</div>
		<div class="col-md-9">
			<%= yield %>
		</div>
	</div>
	</body>
</html>

app/views/offline_schools/index.html.erb
<div id="map">

</div>

app/views/offline_schools/new.html.erb
<div id="map">
	<script> 
	var school_group = new L.LayerGroup();
	var lat = <%= @lat || 0 %>;
	if (lat === 0) {
		alert("Please enter a valid address, city and state");
		window.location = "/"
	}
	else {
	var lng = <%= @lng || 0 %>;
	var url = "/offline_schools.json?lat=" + encodeURIComponent(lat) + "&lng=" + encodeURIComponent(lng);

	createMap();
	function createMap(){
		var map = L.map('map', {
			center:[lat,lng],
			zoom: 11,
			layers: [school_group]
		});
		L.tileLayer('http://{s}.tile.cloudmade.com/f6c127adc91a47f1b4a73837013ed783/998/256/{z}/{x}/{y}.png', {
		  attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://cloudmade.com">CloudMade</a>',
		    maxZoom: 18,
		    minZoom: 1,
		    maxBounds: [[-85, -180], [85, 180]]
		}).addTo(map);
		};
	}
	
	$.ajax({
	    type: "GET",
	    url: url,
	    dataType: 'json',
	    success: function (response) { 
	      for (var i = 0; i < response.length; i++) {
					L.marker([response[i].latitude,response[i].longitude]).openPopup('click').bindPopup(
						"<strong>" + response[i]["name"] + "</strong>" + "<br>" + response[i]["street"] + "<br>" + response[i]["bio"]
					).addTo(school_group);
				}
	    }
	});

	var overlays = {
		"school_group": school_group
	}
	L.control.layers(overlays).addTo(map);

	
	</script>
</div>

app/views/online_schools/_form.html.erb
<%= form_for @online_school do |f| %>	
	<%= f.text_field :name, class: "form-control", placeholder: "Online school/tutorial name" %><br>
	<%= f.text_field :site_url, class: "form-control", placeholder: "Site URL" %><br>
	<%= f.text_field :pricing, class: "form-control", placeholder: "Pricing" %><br>
	<%= f.text_field :bio, class: "form-control", placeholder: "Brief Description" %><br>
	<%= f.text_field :languages, class: "form-control", placeholder: "Languages taught" %><br>
<%= f.submit %>
<% end %>

app/views/online_schools/index.html.erb
<h1><%= link_to "Add a new online school", new_online_school_path %></h1>
<div class="container">
	<% @onlineschools.each do |onlineschool| %>
		<div class="row">
			<div class="col-md-8">
			  <div class="panel panel-default left-col">
			    <div class="panel-heading">
			      <div class="author-bio">
			      	Name: <%= onlineschool.name %><br>	
			      	<a href="<%= onlineschool.site_url %>">Website</a><br>	
			        Languages: <%= onlineschool.languages %><br>
			        Pricing: <%= onlineschool.pricing %><br>	
			      </div>
			    </div>
			    <div class="panel-body">
				  	Description: <%= onlineschool.bio %>
				  </div>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/online_schools/new.html.erb
<h1>Enter an Online School!</h1>
<%= render "form"%>

app/views/quotes/_form.html.erb
<%= form_for @quote do |f| %>	
	Name: <br>
	<%= f.text_field :author, class: "form-group", placeholder: "Enter name" %><br>
	Employer: <br>
	<%= f.text_field :employer, class: "form-group", placeholder: "Enter employer" %><br>
	Position: <br>
	<%= f.text_field :position, class: "form-group", placeholder: "Enter position" %><br>
	Education: <br>
	<%= f.text_field :education, class: "form-group", placeholder: "Enter Education" %><br>
	Years Programming: <br>
	<%= f.text_field :years_programming, class: "form-group", placeholder: "Enter years programming" %><br>
	Picture: <br>
	<%= f.text_field :picture, class: "form-group", placeholder: "Enter picture URL" %><br>
	Words of Wisdom: <br>
	<%= f.text_field :advice, class: "form-group", size: "50x10" %><br>
	<%= f.submit %>
<% end %>

app/views/quotes/_quote.html.erb
<div class="row">
	<div class="col-md-6">
	  <div class="panel panel-default left-col">
	    <div class="panel-heading">
	      <img src='<%= quote.picture %>' class="image pull-right">
	      <div class="author-bio">
	      	Name: <%= quote.author %><br>	
	      	Title: <%= quote.position %><br>	
	        Company: <%= quote.employer %><br>
	        Years Programming: <%= quote.years_programming %><br>	
	      </div>
	    </div>
	    <div class="panel-body">
		  	<%= quote.advice %> 
		  </div>
		</div>
	</div>
</div>

app/views/quotes/index.html.erb
<h1>Anyone can code:</h1>
<div class="quotes-description">Contrary to popular belief, being a successful programmer doesn't require a full computer science degree. In fact, programmers come from all walks of life.</div>

<div class="container">
<% @quotes.each do |quote| %>
		<div class="row">
			<div class="col-md-11">
			  <div class="panel panel-default left-col">
			    <div class="panel-heading">
			      <img src='<%= quote.picture %>' class="image pull-right">
			      <div class="author-bio">
			      	Name: <%= quote.author %><br>	
			      	Title: <%= quote.position %><br>	
			        Company: <%= quote.employer %><br>
			        Years Programming: <%= quote.years_programming %><br>	
			      </div>
			    </div>
			    <div class="panel-body">
				  	<%= quote.advice %> 
				  </div>
				</div>
			</div>
		</div>	
<% end %>
</div>

app/views/quotes/new.html.erb
<h1>Share your wisdom!</h1>
	<%= render "form"%>

app/views/quotes/show.html.erb
<%= render "quote", quote: @quote %>